### DISCUSSION TITLE
A very slow search for knowledge (RAG)

### DISCUSSION THREAD

**Discussion by demon-ru** [open-webui/open-webui#12746] [General]
OpenWebUI v0.6.2
docker with ollama and --gpus all
ubuntu 24.04, rtx 3090 24G

When I first installed this miracle, I was pleasantly surprised by the speed of receiving responses from the "thinking" model (qwq:32b Q4, 20Gb).
But after adding a few relatively small documents to the RAG, everything changed. The search for documents takes a very long time (from a minute and much more).

Fulltext and hybrid search is off.
I tried to change the embed engine: from SentensTransformes to Ollama with several model (the last is paraphrase-multilingual:latest).
I tried to change chromadb to standalone milvus (with gpu support).
Nothing has changed significantly.

I see: When is the search for knowledge (as well as when adding docs) GPU is not used. The CPUs is heavily utilized by the process "ollama runner".

What did I set up incorrectly? What parameters need to be changed to fix this situation?
Thanks

**Comment by vaclcer** [comment]
Similar problem here. The hybrid search is very slow. Even with  small collection it takes at least a minute. Also, 3 queries are being made, why?

Using Elasticsearch as a vector store. Hybrid search via Elastic should be very fast... Using ranker model on CPU, is that the problem? I cannot see that in logs.. Also OWU does not yet support external rankers. Embeddings done externally, should be fast. Generation should be fast as well.

Could somebody more knowledgable tell me what is the bottleneck here? I am just seeing "query_doc_with_hybrid_search" takes forever and CPU is used 100% for all the time evenly by OWU's Unicorn server as well as Elastic.

> 2025-04-24 09:52:51.916 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 127.0.0.1:48112 - "POST /api/v1/chats/bc6c6420-5b94-41cd-aa74-64e7183fa20c HTTP/1.1" 200 - {}
> 2025-04-24 09:52:52.032 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 127.0.0.1:48128 - "GET /api/v1/chats/?page=1 HTTP/1.1" 200 - {}
> 2025-04-24 09:52:52.094 | INFO     | open_webui.routers.openai:get_all_models:389 - get_all_models() - {}
> 2025-04-24 09:52:54.499 | INFO     | elastic_transport._transport:perform_request:349 - POST https://xyz:443/elastic/open_webui_collections*/_search?scroll=5m [status:200 duration:0.187s] - {}
> 2025-04-24 09:52:54.543 | INFO     | elastic_transport._transport:perform_request:349 - POST https://xyz.eu:443/elastic/_search/scroll [status:200 duration:0.031s] - {}
> 2025-04-24 09:52:54.553 | INFO     | elastic_transport._transport:perform_request:349 - DELETE https://xyz:443/elastic/_search/scroll [status:200 duration:0.009s] - {}
> 2025-04-24 09:52:54.555 | INFO     | open_webui.retrieval.utils:query_collection_with_hybrid_search:310 - Starting hybrid search for 3 queries in 1 collections... - {}
> 2025-04-24 09:52:55.003 | INFO     | elastic_transport._transport:perform_request:349 - POST https://xyz.eu:443/elastic/open_webui_collections_d1024/_search [status:200 duration:0.132s] - {}
> 2025-04-24 09:52:55.104 | INFO     | elastic_transport._transport:perform_request:349 - POST https://xyz.eu:443/elastic/open_webui_collections_d1024/_search [status:200 duration:0.213s] - {}
> Batches:   0%|          | 0/1 [00:00<?, ?it/s]
> 2025-04-24 09:52:55.125 | INFO     | elastic_transport._transport:perform_request:349 - POST https://xyz.eu:443/elastic/open_webui_collections_d10Batches: 100%|██████████| 1/1 [00:45<00:00, 45.96s/it]

> 2025-04-24 09:53:41.062 | INFO     | open_webui.retrieval.utils:query_doc_with_hybrid_search:168 - query_doc_with_hybrid_search:result [[{'name': 'XXX29061-i10.pdf', 'content_type': 'application/pdf', 'size': 5279825, 'data': '{}', 'collection_name': 'file-7cc7db02-fc09-44d8-9ca1-0df148985776', 'created_by': '74e586c1-4851-49be-9c83-2a52d52e8e62', 'file_id': '7cc7db02-fc09-44d8-9ca1-0df148985776', 'source': 'XXX29061-i10.pdf', 'start_index': 182519, 'hash': 'b04d809026e39761c651d524f6cd7dc4bcfd1f6e6aff46b29bdd76d0a86752c7', 'embedding_config': '{"engine": "openai", "model": "snowflake-arctic-embed-l-v2.0"}', 'score': 0.8916621804237366}, {'name': 'XXX29061-i10.pdf', 'content_type': 'application/pdf', 'size': 5279825, 'data': '{}', 'collection_name': 'file-7cc7db02-fc09-44d8-9ca1-0df148985776', 'created_by': '74e586c1-4851-49be-9c83-2a52d52e8e62', 'file_id': '7cc7db02-fc09-44d8-9ca1-0df148985776', 'source': 'XXX29061-i10.pdf', 'start_index': 202866, 'hash': 'b04d809026e39761c651d524f6cd7dc4bcfd1f6e6aff46b29bdd76d0a86752c7', 'embedding_config': '{"engine": "openai", "model": "snowflake-arctic-embed-l-v2.0"}', 'score': 0.883240282535553}, {'name': 'XXX29061-i10.pdf', 'content_type': 'application/pdf', 'size': 5279825, 'data': '{}', 'collection_name': 'file-7cc7db02-fc09-44d8-9ca1-0df148985776', 'created_by': '74e586c1-4851-49be-9c83-2a52d52e8e62', 'file_id': '7cc7db02-fc09-44d8-9ca1-0df148985776', 'source': 'XXX29061-i10.pdf', 'start_index': 178170, 'hash': 'b04d809026e39761c651d524f6cd7dc4bcfd1f6e6aff46b29bdd76d0a86752c7', 'embedding_config': '{"engine": "openai", "model": "snowflake-arctic-embed-l-v2.0"}', 'score': 0.8683862686157227}, {'name': 'XXX29061-i10.pdf', 'content_type': 'application/pdf', 'size': 5279825, 'data': '{}', 'collection_name': 'file-7cc7db02-fc09-44d8-9ca1-0df148985776', 'created_by': '74e586c1-4851-49be-9c83-2a52d52e8e62', 'file_id': '7cc7db02-fc09-44d8-9ca1-0df148985776', 'source': 'XXX29061-i10.pdf', 'start_index': 197789, 'hash': 'b04d809026e39761c651d524f6cd7dc4bcfd1f6e6aff46b29bdd76d0a86752c7', 'embedding_config': '{"engine": "openai", "model": "snowflake-arctic-embed-l-v2.0"}', 'score': 0.8613553643226624}, {'name': 'XXX29061-i10.pdf', 'content_type': 'application/pdf', 'size': 5279825, 'data': '{}', 'collection_name': 'file-7cc7db02-fc09-44d8-9ca1-0df148985776', 'created_by': '74e586c1-4851-49be-9c83-2a52d52e8e62', 'file_id': '7cc7db02-fc09-44d8-9ca1-0df148985776', 'source': 'XXX29061-i10.pdf', 'start_index': 268454, 'hash': 'b04d809026e39761c651d524f6cd7dc4bcfd1f6e6aff46b29bdd76d0a86752c7', 'embedding_config': '{"engine": "openai", "model": "snowflake-arctic-embed-l-v2.0"}', 'score': 0.8568883538246155}]] [[0.8916621804237366, 0.883240282535553, 0.8683862686157227, 0.8613553643226624, 0.8568883538246155]] - {}

> Batches: 100%|██████████| 1/1 [00:46<00:00, 46.61s/it]

> 2025-04-24 09:53:41.767 | INFO     | open_webui.retrieval.utils:query_doc_with_hybrid_search:168 - query_doc_with_hybrid_search:result [[{'name': 'XXX29061-i10.pdf', 'content_type': 'application/pdf', 'size': 5279825, 'data': '{}', 'collection_name': 'file-7cc7db02-fc09-44d8-9ca1-0df148985776', 'created_by': '74e586c1-4851-49be-9c83-2a52d52e8e62', 'file_id': '7cc7db02-fc09-44d8-9ca1-0df148985776', 'source': 'XXX29061-i10.pdf', 'start_index': 150513, 'hash': 'b04d809026e39761c651d524f6cd7dc4bcfd1f6e6aff46b29bdd76d0a86752c7', 'embedding_config': '{"engine": "openai", "model": "snowflake-arctic-embed-l-v2.0"}', 'score': 0.8612189292907715}, {'name': 'XXX29061-i10.pdf', 'content_type': 'application/pdf', 'size': 5279825, 'data': '{}', 'collection_name': 'file-7cc7db02-fc09-44d8-9ca1-0df148985776', 'created_by': '74e586c1-4851-49be-9c83-2a52d52e8e62', 'file_id': '7cc7db02-fc09-44d8-9ca1-0df148985776', 'source': 'XXX29061-i10.pdf', 'start_index': 157755, 'hash': 'b04d809026e39761c651d524f6cd7dc4bcfd1f6e6aff46b29bdd76d0a86752c7', 'embedding_config': '{"engine": "openai", "model": "snowflake-arctic-embed-l-v2.0"}', 'score': 0.8454981446266174}, {'name': 'XXX29061-i10.pdf', 'content_type': 'application/pdf', 'size': 5279825, 'data': '{}', 'collection_name': 'file-7cc7db02-fc09-44d8-9ca1-0df148985776', 'created_by': '74e586c1-4851-49be-9c83-2a52d52e8e62', 'file_id': '7cc7db02-fc09-44d8-9ca1-0df148985776', 'source': 'XXX29061-i10.pdf', 'start_index': 133013, 'hash': 'b04d809026e39761c651d524f6cd7dc4bcfd1f6e6aff46b29bdd76d0a86752c7', 'embedding_config': '{"engine": "openai", "model": "snowflake-arctic-embed-l-v2.0"}', 'score': 0.8362817168235779}, {'name': 'XXX29061-i10.pdf', 'content_type': 'application/pdf', 'size': 5279825, 'data': '{}', 'collection_name': 'file-7cc7db02-fc09-44d8-9ca1-0df148985776', 'created_by': '74e586c1-4851-49be-9c83-2a52d52e8e62', 'file_id': '7cc7db02-fc09-44d8-9ca1-0df148985776', 'source': 'XXX29061-i10.pdf', 'start_index': 165035, 'hash': 'b04d809026e39761c651d524f6cd7dc4bcfd1f6e6aff46b29bdd76d0a86752c7', 'embedding_config': '{"engine": "openai", "model": "snowflake-arctic-embed-l-v2.0"}', 'score': 0.8289154767990112}, {'name': 'XXX29061-i10.pdf', 'content_type': 'application/pdf', 'size': 5279825, 'data': '{}', 'collection_name': 'file-7cc7db02-fc09-44d8-9ca1-0df148985776', 'created_by': '74e586c1-4851-49be-9c83-2a52d52e8e62', 'file_id': '7cc7db02-fc09-44d8-9ca1-0df148985776', 'source': 'XXX29061-i10.pdf', 'start_index': 137394, 'hash': 'b04d809026e39761c651d524f6cd7dc4bcfd1f6e6aff46b29bdd76d0a86752c7', 'embedding_config': '{"engine": "openai", "model": "snowflake-arctic-embed-l-v2.0"}', 'score': 0.8207889795303345}]] [[0.8612189292907715, 0.8454981446266174, 0.8362817168235779, 0.8289154767990112, 0.8207889795303345]] - {}

> Batches: 100%|██████████| 1/1 [00:54<00:00, 54.24s/it]

> 2025-04-24 09:53:49.389 | INFO     | open_webui.retrieval.utils:query_doc_with_hybrid_search:168 - query_doc_with_hybrid_search:result [[{'name': 'XXX29061-i10.pdf', 'content_type': 'application/pdf', 'size': 5279825, 'data': '{}', 'collection_name': 'file-7cc7db02-fc09-44d8-9ca1-0df148985776', 'created_by': '74e586c1-4851-49be-9c83-2a52d52e8e62', 'file_id': '7cc7db02-fc09-44d8-9ca1-0df148985776', 'source': 'XXX29061-i10.pdf', 'start_index': 230593, 'hash': 'b04d809026e39761c651d524f6cd7dc4bcfd1f6e6aff46b29bdd76d0a86752c7', 'embedding_config': '{"engine": "openai", "model": "snowflake-arctic-embed-l-v2.0"}', 'score': 0.8116528391838074}, {'name': 'XXX29061-i10.pdf', 'content_type': 'application/pdf', 'size': 5279825, 'data': '{}', 'collection_name': 'file-7cc7db02-fc09-44d8-9ca1-0df148985776', 'created_by': '74e586c1-4851-49be-9c83-2a52d52e8e62', 'file_id': '7cc7db02-fc09-44d8-9ca1-0df148985776', 'source': 'XXX29061-i10.pdf', 'start_index': 137394, 'hash': 'b04d809026e39761c651d524f6cd7dc4bcfd1f6e6aff46b29bdd76d0a86752c7', 'embedding_config': '{"engine": "openai", "model": "snowflake-arctic-embed-l-v2.0"}', 'score': 0.7676497101783752}, {'name': 'XXX29061-i10.pdf', 'content_type': 'application/pdf', 'size': 5279825, 'data': '{}', 'collection_name': 'file-7cc7db02-fc09-44d8-9ca1-0df148985776', 'created_by': '74e586c1-4851-49be-9c83-2a52d52e8e62', 'file_id': '7cc7db02-fc09-44d8-9ca1-0df148985776', 'source': 'XXX29061-i10.pdf', 'start_index': 672469, 'hash': 'b04d809026e39761c651d524f6cd7dc4bcfd1f6e6aff46b29bdd76d0a86752c7', 'embedding_config': '{"engine": "openai", "model": "snowflake-arctic-embed-l-v2.0"}', 'score': 0.7595289945602417}, {'name': 'XXX29061-i10.pdf', 'content_type': 'application/pdf', 'size': 5279825, 'data': '{}', 'collection_name': 'file-7cc7db02-fc09-44d8-9ca1-0df148985776', 'created_by': '74e586c1-4851-49be-9c83-2a52d52e8e62', 'file_id': '7cc7db02-fc09-44d8-9ca1-0df148985776', 'source': 'XXX29061-i10.pdf', 'start_index': 91189, 'hash': 'b04d809026e39761c651d524f6cd7dc4bcfd1f6e6aff46b29bdd76d0a86752c7', 'embedding_config': '{"engine": "openai", "model": "snowflake-arctic-embed-l-v2.0"}', 'score': 0.7478477954864502}, {'name': 'XXX29061-i10.pdf', 'content_type': 'application/pdf', 'size': 5279825, 'data': '{}', 'collection_name': 'file-7cc7db02-fc09-44d8-9ca1-0df148985776', 'created_by': '74e586c1-4851-49be-9c83-2a52d52e8e62', 'file_id': '7cc7db02-fc09-44d8-9ca1-0df148985776', 'source': 'XXX29061-i10.pdf', 'start_index': 8441, 'hash': 'b04d809026e39761c651d524f6cd7dc4bcfd1f6e6aff46b29bdd76d0a86752c7', 'embedding_config': '{"engine": "openai", "model": "snowflake-arctic-embed-l-v2.0"}', 'score': 0.7327866554260254}]] [[0.8116528391838074, 0.7676497101783752, 0.7595289945602417, 0.7478477954864502, 0.7327866554260254]] - {}

> 2025-04-24 09:53:49.482 | INFO     | open_webui.routers.openai:get_all_models:389 - get_all_models() - {}
> 2025-04-24 09:53:50.001 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 127.0.0.1:48144 - "POST /api/chat/completions HTTP/1.1" 200 - {}
> 2025-04-24 09:53:50.112 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 127.0.0.1:53328 - "GET /api/v1/chats/?page=1 HTTP/1.1" 200 - {}

**Comment by arunbugkiller** [comment]
@vaclcer @demon-ru Were you able to pin-point and resolve the issue?

**Reply by demon-ru** [reply]
No. Currently, using "embedded" RAG (Chroma) and hybrid search with embedded (SentenceTransformers) is very slow.
htop shows dozens of processes occupying all processor cores.
I haven't found any instructions for solving this problem yet. I understand that the built-in (SentenceTransformers) does not use the GPU. 

When switching to an external engine when specifying the address "http://localhost:11434/api/embeddings " or "http://localhost:11434 " I got errors: "the method is not supported".
I tried to install Milvus, I planned to try qdrant. I don't know if this will solve my problem yet.

P.S. The number of knowledge grew to 10, and the total number of documents reached tens of thousands (small documents)

**Reply by rgaricano** [reply]
SentenceTransformers use GPU if  env var USE_CUDA_DOCKER="true" is setted.

**Reply by demon-ru** [reply]
> SentenceTransformers use GPU if env var USE_CUDA_DOCKER="true" is setted.

stop and rm container.
run:
docker run -d -p 3000:8080 -e ENV=dev \
  --gpus=all \
  -e OLLAMA_GPU=1 \
  -e USE_CUDA_DOCKER=1 \
  -v ollama:/root/.ollama \
  -v open-webui:/app/backend/data \
  --name open-webui --restart always ghcr.io/open-webui/open-webui:ollama

Nothing has changed. 100% CPU used and where are a lot of:
/usr/local/bin/python3 -m uvicorn open_webui.main:app --host 0.0.0.0 --port 8080 --forwarded-allow-ips * --workers 1

What other reason could there be for not using the GPU?
What can I look at in docker logs to find out the reason?
Thanks

**Reply by rgaricano** [reply]
Maybe somebody that use docker can help better,  i'm not using docker.

But maybe you can try with cuda support image: ghcr.io/open-webui/open-webui:v0.6.18-cuda
& separate ollama 
(not sure if  open-webui:ollama package have gpu support)

**Comment by vaclcer** [comment]
Yes. In my case, it was reranking done on CPU. Since OWU supports external reranking now, its no longer an issue for me.

**Reply by demon-ru** [reply]
Please tell me how can I set up an external reranker? Perhaps there is an instruction about this?

**Reply by vaclcer** [reply]
It depends, but reranking (and embedding) must run on GPU or via external API (Cohere etc.). Every situation is a bit different..

**Reply by rgaricano** [reply]
SentenceTransformers use GPU if  env var USE_CUDA_DOCKER="true" is setted.

**Reply by apunkt** [reply]
> SentenceTransformers use GPU if env var USE_CUDA_DOCKER="true" is setted.

This worked for me in a native install with Qdrant, but stopped working 2-3 updates ago.
The process is not visible in nvtop anymore.

**Reply by arunbugkiller** [reply]
@vaclcer which external re-ranker are you using?

**Reply by apunkt** [reply]
> > SentenceTransformers use GPU if env var USE_CUDA_DOCKER="true" is setted.
> 
> This worked for me in a native install with Qdrant, but stopped working 2-3 updates ago. The process is not visible in nvtop anymore.

Investigation result: a previous version update reset the reranking model to None - which worked then without error or warning (how?) and terribly slow.

**Comment by demon-ru** [comment]
I have achieved the desired result. What is needed for this:
1. use the cuda image
docker run -d -p 3000:8080 --gpus all -v open-webui:/app/backend/data --name open-webui ghcr.io/open-webui/open-webui:cuda
https://docs.openwebui.com/getting-started/quick-start
And this means without using the built-in ollama. I had to use a separate installation (but it's not difficult at all).
https://ollama.com/download

2. when starting docker, you must specify the parameter -e USE_CUDA_DOCKER=true. And it is "true", not "1".
docker run -d -p 3000:8080 --gpus all -e USE_CUDA_DOCKER=true -v open-webui:/app/backend/data --name open-webui ghcr.io/open-webui/open-webui:cuda

At the same time, you need to be prepared that GPU memory will start using not only hybrid search, but also RAG (chroma?)

**Reply by arunbugkiller** [reply]
@demon-ru what is knowledge base size (#, count of documents) you are using?
How is the current retrieval accuracy and latency? Which models (extraction engine, embedding, LLM and re-ranker (if you used) would work best) 

I currently have about 5k documents (medium to complex structure), sitting across multiple collections and using nomic embed text large (Ollama), gpt-4.1(LiteLLM) and no-reranker - all hosted on 16core 32GB RAM (CPU) server and have issue mainly with retrieval accuracy
