### DISCUSSION TITLE
issue: Attaching file to a prompt produces a CUDA error

### DISCUSSION THREAD

**Discussion by Nexxsys** [open-webui/open-webui#13593] [Issues]
### Check Existing Issues

- [x] I have searched the existing issues and discussions.
- [x] I am using the latest version of Open WebUI.

### Installation Method

Docker

### Open WebUI Version

v0.6.6 - 2025-05-05

### Ollama Version (if applicable)

3.2:Latest

### Operating System

Linux Mint 12

### Browser (if applicable)

Brave

### Confirmation

- [x] I have read and followed all instructions in `README.md`.
- [x] I am using the latest version of **both** Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have listed steps to reproduce the bug in detail.

### Expected Behavior

File is attached with no error.

### Actual Behavior

Attaching a file to a prompt produces this error: CUDA error: no kernel image is available for execution on the device CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1 Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### Steps to Reproduce

At the prompt, click the plus sign Upload Files, and select any file of any type to produce the error

### Logs & Screenshots

  File "/usr/local/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 1080, in forward
    embedding_output = self.embeddings(
                       └ BertModel(
                           (embeddings): BertEmbeddings(
                             (word_embeddings): Embedding(30522, 384, padding_idx=0)
                             (position_embeddin...
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           │    │           │       └ <unprintable dict object>
           │    │           └ ()
           │    └ <function Module._call_impl at 0x7d591af7c9a0>
           └ BertEmbeddings(
               (word_embeddings): Embedding(30522, 384, padding_idx=0)
               (position_embeddings): Embedding(512, 384)
               (tok...
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           │             │       └ <unprintable dict object>
           │             └ ()
           └ <bound method BertEmbeddings.forward of BertEmbeddings(
               (word_embeddings): Embedding(30522, 384, padding_idx=0)
               (position...
  File "/usr/local/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 211, in forward
    inputs_embeds = self.word_embeddings(input_ids)
                    │                    └ <unprintable Tensor object>
                    └ BertEmbeddings(
                        (word_embeddings): Embedding(30522, 384, padding_idx=0)
                        (position_embeddings): Embedding(512, 384)
                        (tok...
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           │    │           │       └ {}
           │    │           └ <unprintable tuple object>
           │    └ <function Module._call_impl at 0x7d591af7c9a0>
           └ Embedding(30522, 384, padding_idx=0)
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           │             │       └ {}
           │             └ <unprintable tuple object>
           └ <bound method Embedding.forward of Embedding(30522, 384, padding_idx=0)>
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/sparse.py", line 190, in forward
    return F.embedding(
           │ └ <function embedding at 0x7d5915bb6700>
           └ <module 'torch.nn.functional' from '/usr/local/lib/python3.11/site-packages/torch/nn/functional.py'>
  File "/usr/local/lib/python3.11/site-packages/torch/nn/functional.py", line 2551, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
           │     │         │       │      │            │                   └ False
           │     │         │       │      │            └ False
           │     │         │       │      └ 0
           │     │         │       └ <unprintable Tensor object>
           │     │         └ <unprintable Parameter object>
           │     └ <built-in method embedding of type object at 0x7d5a208d8f80>
           └ <module 'torch' from '/usr/local/lib/python3.11/site-packages/torch/__init__.py'>
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7d5a31bac860>
    └ <WorkerThread(AnyIO worker thread, started 137818412148416)>
  File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
    │    └ <function WorkerThread.run at 0x7d58851c6200>
    └ <WorkerThread(AnyIO worker thread, started 137818412148416)>
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 967, in run
    result = context.run(func, *args)
             │       │   │      └ ()
             │       │   └ functools.partial(<function upload_file at 0x7d58f0bc8400>, user=UserModel(id='60b2ead4-73fa-43bc-a0ff-8538523c50f7', name='T...
             │       └ <method 'run' of '_contextvars.Context' objects>
             └ <_contextvars.Context object at 0x7d5885172a80>
> File "/app/backend/open_webui/routers/files.py", line 155, in upload_file
    process_file(request, ProcessFileForm(file_id=id), user=user)
    │            │        │                       │         └ UserModel(id='60b2ead4-73fa-43bc-a0ff-8538523c50f7', name='"', email='"', role='admin', profile_imag...
    │            │        │                       └ '3dc97043-7027-4834-8ab3-882df54778c0'
    │            │        └ <class 'open_webui.routers.retrieval.ProcessFileForm'>
    │            └ <starlette.requests.Request object at 0x7d5884db2e90>
    └ <function process_file at 0x7d58dd84ccc0>
  File "/app/backend/open_webui/routers/retrieval.py", line 1194, in process_file
    raise HTTPException(
          └ <class 'fastapi.exceptions.HTTPException'>
fastapi.exceptions.HTTPException: 400: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
2025-05-06 19:57:33.737 | ERROR    | open_webui.routers.files:upload_file:160 - Error processing file: 3dc97043-7027-4834-8ab3-882df54778c0 - {}
2025-05-06 19:57:33.738 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.0.159:14711 - "POST /api/v1/files/ HTTP/1.1" 200 - {}

### Additional Information

 NVIDIA-SMI 550.144.03             Driver Version: 550.144.03     CUDA Version: 12.4

**Comment by Nexxsys** [comment]
I have reverted by to version 0.6.5 and the issue does not exist with that version.

**Reply by niichavodev** [reply]
thank you! this saved a lot of time for me!

**Comment by ghost** [comment]
Hi!

I’ve run into exactly the same problem using Open WebUI v0.6.9 in a Docker container on a GTX 1050 Ti: whenever I try to attach any file, I get the error

```
CUDA error: no kernel image is available for execution on the device…
```

It turns out that PyTorch 2.x+ no longer supports the Pascal architecture (sm\_61), and I’m not planning to upgrade my GPU anytime soon.

So I kindly ask you to please restore support for older graphics cards (sm\_61) or provide a way to explicitly build for them (for example, via `TORCH_CUDA_ARCH_LIST` or similar). Without this, most users with older hardware simply won’t be able to use your UI, even though laptops and desktops with GTX 10xx GPUs are still in widespread use.

Thanks in advance for your attention, and I hope for a positive solution!

**Reply by HotshotGT** [reply]
I'm also running into this same error on a P102-100 that was working fine prior to updating from v0.6.5.

I imagine a lot of people are offloading RAG to an older spare GPU to free up VRAM on their primary card for larger models. It'd be a shame to drop support for them when even mid-range Pascal cards are more than enough for basic embedding and reranking models.

**Reply by Nexxsys** [reply]
Thanks @AliveDedSec  for elucidating why this has come about.  I am not planning on upgrading my GPU either for the time being (considering the prices).

**Reply by ghost** [reply]
> As a workaround, I use KOBOLDCPP for text vectorization with `TRoTR-paraphrase-multilingual-MiniLM-L12-v2.Q8_0.gguf`, selected in the Loaded Files tab under the **Embeds Model** field, by pointing to an OpenAI-compatible endpoint for vectorization in Open WebUI.
>
> My setup is as follows:
>
> - **OpenAI Embedding Model Engine:** `http://0.0.0.0:5058/v1`
> - **Embedding Model:** `TRoTR-paraphrase-multilingual-MiniLM-L12-v2.Q8_0`
>
> I also run a Docker container for content extraction:
>
> - **Content Extraction Engine:** Apache Tika at `http://0.0.0.0:9998/`
>
> Tika installation:
> ```bash
> docker pull apache/tika:latest-full
> docker run -d --name tika-server -p 9998:9998 apache/tika:latest-full
> ```
>
> Enter the container as root and install OCR support:
> ```bash
> docker exec -it tika-server bash
> apt update && apt install -y tesseract-ocr tesseract-ocr-eng tesseract-ocr-rus
> ```
> - `apt-get update` — updates package lists  
> - `apt-get install -y tesseract-ocr-eng tesseract-ocr-rus` — installs English and Russian language packs
>
> Verify available Tesseract languages:
> ```bash
> tesseract --list-langs
> ```
> Output should include:
> ```
> eng
> rus
> ```
>
> Everything works on the latest version!
>
> I also use Whisper via KoboldCPP with silence removal to avoid glitches.  
> Here is my mini-server script for Open WebUI ↔ KoboldCPP compatibility, in case someone finds it useful:  
[OPEN-WEBUI+KOBOLDCPP-DLYA-WHISPER-proxy.py .TXT](https://github.com/user-attachments/files/20321098/OPEN-WEBUI%2BKOBOLDCPP-DLYA-WHISPER-proxy.py.TXT)    

https://huggingface.co/ggerganov/whisper.cpp/tree/main

**Reply by HotshotGT** [reply]
I ended up configuring [Infinity](https://github.com/michaelfeil/infinity) and moving back to the non-cuda Open WebUI container. All I had to do was configure what models I wanted in the container arguments and set the docker network address for the external embedding/reranking engines.

My only frustration with the process is that Open WebUI seems to force an "embeddings" endpoint on whatever URL you provide, but requires you to specify a "rerank" endpoint manually. Combine that inconsistency with a lack of confirmation that the endpoints are valid and a useless repeating notification that the model name was saved successfully, and you're stuck refreshing the page and going in/out of the admin panel to see if the settings actually stuck.

**Reply by rwachters** [reply]
When using CUDA 12.1 it works on GTX 1xxx cards:

```
# syntax=docker/dockerfile:1
# Initialize device type args
# use build args in the docker build command with --build-arg="BUILDARG=true"
ARG USE_CUDA=true
ARG USE_OLLAMA=false
# Tested with cu117 for CUDA 11 and cu121 for CUDA 12 (default)
ARG USE_CUDA_VER=cu121
```

the problem is that it was changed from cu121 to cu128.. to support 5090 cards i think

link to pull request: https://github.com/open-webui/open-webui/pull/13187

**Reply by Nexxsys** [reply]
Didn't work for me, ran it new errors and issues.  I have decided to retire my GTX 1070 and go with a Turing or newer generation card instead.    References for supported GPU and cuda versions: [https://developer.nvidia.com/cuda-gpus](url) and [https://docs.nvidia.com/deeplearning/cudnn/backend/latest/reference/support-matrix.html#f5](url)

**Comment by Nexxsys** [comment]
According to @AliveDedSec  and here: [https://docs.nvidia.com/deeplearning/cudnn/backend/latest/reference/support-matrix.html#f5](url) footnote # 5, the Pascal gpus are not supported on the latest cuda version.  Switching to a Turing or newer generation GPU has resolved this issue for me.

**Comment by ghost** [comment]
https://github.com/open-webui/open-webui/pkgs/container/open-webui/438267102?tag=dev-cuda126               🛠️ CUDA 12.6 Docker Image Support: Deploy to NVIDIA GPUs with capability 7.0 and below (e.g., V100, GTX1080) via new cuda126 image—broadening your hardware options for scalable AI workloads.
