### DISCUSSION TITLE
issue: dgx, CTranslate2 package was not compiled with CUDA support in open-webui:cuda

### DISCUSSION THREAD

**Discussion by chris4prez** [open-webui/open-webui#18931] [Issues]
### Check Existing Issues

- [x] I have searched for any existing and/or related issues.
- [x] I have searched for any existing and/or related discussions.
- [x] I am using the latest version of Open WebUI.

### Installation Method

Docker

### Open WebUI Version

open-webui:cuda

### Operating System

Ubuntu 24.04

### Confirmation

- [x] I have read and followed all instructions in `README.md`.
- [x] I am using the latest version of **both** Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have **provided every relevant configuration, setting, and environment variable used in my setup.**
- [x] I have clearly **listed every relevant configuration, custom setting, environment variable, and command-line option that influences my setup** (such as Docker Compose overrides, .env values, browser settings, authentication configurations, etc).
- [x] I have documented **step-by-step reproduction instructions that are precise, sequential, and leave nothing to interpretation**. My steps:
- Start with the initial platform/version/OS and dependencies used,
- Specify exact install/launch/configure commands,
- List URLs visited, user input (incl. example values/emails/passwords if needed),
- Describe all options and toggles enabled or changed,
- Include any files or environmental changes,
- Identify the expected and actual result at each stage,
- Ensure any reasonably skilled user can follow and hit the same issue.

### Expected Behavior

I should be able to use speech to text. CPU contiainer works with no issues. 

I am running on a DGX Spark which is fully setup for CUDA and have GPU confirmed working within docker via vLLM. nvidia-smi works within the openwebui container.

### Actual Behavior

ERROR    | open_webui.routers.audio:transcription:1002 - 500: Error transcribing chunk: This CTranslate2 package was not compiled with CUDA support

Is stated within the container logs when I attempt to use speech to text.

### Steps to Reproduce

compose.yaml is the following:

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:cuda
    container_name: open-webui
    volumes:
      - open-webui_data:/app/backend/data
    networks:
      llm:
      proxy:
    environment:
      - OPENAI_API_BASE_URL=http://vllm-llm:8000/v1
      - OPENAI_API_KEY=8675309Jenny
      - WEBUI_SECRET_KEY=Jenny8675309
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: "all"
              capabilities: ["gpu"]
    restart: always

networks:
  llm:
    name: llm
  proxy:
    name: proxy

volumes:
  open-webui_data:
    name: open-webui_data

### Logs & Screenshots

Container Logs

CUDA is enabled, appending LD_LIBRARY_PATH to include torch/cudnn & cublas libraries.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [open_webui.env] 'ENABLE_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'ENABLE_API_KEY_ENDPOINT_RESTRICTIONS' loaded from the latest database entry
INFO  [open_webui.env] 'API_KEY_ALLOWED_ENDPOINTS' loaded from the latest database entry
INFO  [open_webui.env] 'JWT_EXPIRES_IN' loaded from the latest database entry
INFO  [open_webui.env] 'ENABLE_OLLAMA_API' loaded from the latest database entry
INFO  [open_webui.env] 'OLLAMA_BASE_URLS' loaded from the latest database entry
INFO  [open_webui.env] 'OLLAMA_API_CONFIGS' loaded from the latest database entry
INFO  [open_webui.env] 'ENABLE_OPENAI_API' loaded from the latest database entry
INFO  [open_webui.env] 'OPENAI_API_KEYS' loaded from the latest database entry
INFO  [open_webui.env] 'OPENAI_API_BASE_URLS' loaded from the latest database entry
INFO  [open_webui.env] 'OPENAI_API_CONFIGS' loaded from the latest database entry
INFO  [open_webui.env] 'TOOL_SERVER_CONNECTIONS' loaded from the latest database entry
INFO  [open_webui.env] 'WEBUI_URL' loaded from the latest database entry
INFO  [open_webui.env] 'ENABLE_SIGNUP' loaded from the latest database entry
INFO  [open_webui.env] 'DEFAULT_USER_ROLE' loaded from the latest database entry
INFO  [open_webui.env] 'PENDING_USER_OVERLAY_TITLE' loaded from the latest database entry
INFO  [open_webui.env] 'PENDING_USER_OVERLAY_CONTENT' loaded from the latest database entry
INFO  [open_webui.env] 'RESPONSE_WATERMARK' loaded from the latest database entry
INFO  [open_webui.env] 'ENABLE_CHANNELS' loaded from the latest database entry
INFO  [open_webui.env] 'ENABLE_NOTES' loaded from the latest database entry
INFO  [open_webui.env] 'ENABLE_EVALUATION_ARENA_MODELS' loaded from the latest database entry
INFO  [open_webui.env] 'EVALUATION_ARENA_MODELS' loaded from the latest database entry
INFO  [open_webui.env] 'WEBHOOK_URL' loaded from the latest database entry
INFO  [open_webui.env] 'ENABLE_COMMUNITY_SHARING' loaded from the latest database entry
INFO  [open_webui.env] 'ENABLE_MESSAGE_RATING' loaded from the latest database entry
INFO  [open_webui.env] 'ENABLE_USER_WEBHOOKS' loaded from the latest database entry
WARNI [open_webui.env] 

WARNING: CORS_ALLOW_ORIGIN IS SET TO '*' - NOT RECOMMENDED FOR PRODUCTION DEPLOYMENTS.

INFO  [open_webui.env] 'SHOW_ADMIN_DETAILS' loaded from the latest database entry
INFO  [open_webui.env] VECTOR_DB: chroma
INFO  [open_webui.env] 'ENABLE_GOOGLE_DRIVE_INTEGRATION' loaded from the latest database entry
INFO  [open_webui.env] 'ENABLE_ONEDRIVE_INTEGRATION' loaded from the latest database entry
INFO  [open_webui.env] 'CONTENT_EXTRACTION_ENGINE' loaded from the latest database entry
INFO  [open_webui.env] 'DATALAB_MARKER_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'DATALAB_MARKER_API_BASE_URL' loaded from the latest database entry
INFO  [open_webui.env] 'DATALAB_MARKER_ADDITIONAL_CONFIG' loaded from the latest database entry
INFO  [open_webui.env] 'DATALAB_MARKER_USE_LLM' loaded from the latest database entry
INFO  [open_webui.env] 'DATALAB_MARKER_SKIP_CACHE' loaded from the latest database entry
INFO  [open_webui.env] 'DATALAB_MARKER_FORCE_OCR' loaded from the latest database entry
INFO  [open_webui.env] 'DATALAB_MARKER_PAGINATE' loaded from the latest database entry
INFO  [open_webui.env] 'DATALAB_MARKER_STRIP_EXISTING_OCR' loaded from the latest database entry
INFO  [open_webui.env] 'DATALAB_MARKER_DISABLE_IMAGE_EXTRACTION' loaded from the latest database entry
INFO  [open_webui.env] 'DATALAB_MARKER_FORMAT_LINES' loaded from the latest database entry
INFO  [open_webui.env] 'DATALAB_MARKER_OUTPUT_FORMAT' loaded from the latest database entry
INFO  [open_webui.env] 'MINERU_API_MODE' loaded from the latest database entry
INFO  [open_webui.env] 'MINERU_API_URL' loaded from the latest database entry
INFO  [open_webui.env] 'MINERU_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'MINERU_PARAMS' loaded from the latest database entry
INFO  [open_webui.env] 'EXTERNAL_DOCUMENT_LOADER_URL' loaded from the latest database entry
INFO  [open_webui.env] 'EXTERNAL_DOCUMENT_LOADER_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'TIKA_SERVER_URL' loaded from the latest database entry
INFO  [open_webui.env] 'DOCLING_SERVER_URL' loaded from the latest database entry
INFO  [open_webui.env] 'DOCLING_PARAMS' loaded from the latest database entry
INFO  [open_webui.env] 'DOCLING_DO_OCR' loaded from the latest database entry
INFO  [open_webui.env] 'DOCLING_FORCE_OCR' loaded from the latest database entry
INFO  [open_webui.env] 'DOCLING_OCR_ENGINE' loaded from the latest database entry
INFO  [open_webui.env] 'DOCLING_OCR_LANG' loaded from the latest database entry
INFO  [open_webui.env] 'DOCLING_PDF_BACKEND' loaded from the latest database entry
INFO  [open_webui.env] 'DOCLING_TABLE_MODE' loaded from the latest database entry
INFO  [open_webui.env] 'DOCLING_PIPELINE' loaded from the latest database entry
INFO  [open_webui.env] 'DOCLING_DO_PICTURE_DESCRIPTION' loaded from the latest database entry
INFO  [open_webui.env] 'DOCLING_PICTURE_DESCRIPTION_MODE' loaded from the latest database entry
INFO  [open_webui.env] 'DOCLING_PICTURE_DESCRIPTION_LOCAL' loaded from the latest database entry
INFO  [open_webui.env] 'DOCLING_PICTURE_DESCRIPTION_API' loaded from the latest database entry
INFO  [open_webui.env] 'DOCUMENT_INTELLIGENCE_ENDPOINT' loaded from the latest database entry
INFO  [open_webui.env] 'DOCUMENT_INTELLIGENCE_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'MISTRAL_OCR_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'BYPASS_EMBEDDING_AND_RETRIEVAL' loaded from the latest database entry
INFO  [open_webui.env] 'RAG_TOP_K' loaded from the latest database entry
INFO  [open_webui.env] 'RAG_TOP_K_RERANKER' loaded from the latest database entry
INFO  [open_webui.env] 'RAG_RELEVANCE_THRESHOLD' loaded from the latest database entry
INFO  [open_webui.env] 'RAG_HYBRID_BM25_WEIGHT' loaded from the latest database entry
INFO  [open_webui.env] 'ENABLE_RAG_HYBRID_SEARCH' loaded from the latest database entry
INFO  [open_webui.env] 'RAG_FULL_CONTEXT' loaded from the latest database entry
INFO  [open_webui.env] 'RAG_ALLOWED_FILE_EXTENSIONS' loaded from the latest database entry
INFO  [open_webui.env] 'PDF_EXTRACT_IMAGES' loaded from the latest database entry
INFO  [open_webui.env] Embedding model set: sentence-transformers/all-MiniLM-L6-v2
INFO  [open_webui.env] 'RAG_RERANKING_ENGINE' loaded from the latest database entry
INFO  [open_webui.env] 'RAG_RERANKING_MODEL' loaded from the latest database entry
INFO  [open_webui.env] 'RAG_EXTERNAL_RERANKER_URL' loaded from the latest database entry
INFO  [open_webui.env] 'RAG_EXTERNAL_RERANKER_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'RAG_TEXT_SPLITTER' loaded from the latest database entry
INFO  [open_webui.env] 'CHUNK_SIZE' loaded from the latest database entry
INFO  [open_webui.env] 'CHUNK_OVERLAP' loaded from the latest database entry
INFO  [open_webui.env] 'RAG_TEMPLATE' loaded from the latest database entry
INFO  [open_webui.env] 'YOUTUBE_LOADER_LANGUAGE' loaded from the latest database entry
INFO  [open_webui.env] 'YOUTUBE_LOADER_PROXY_URL' loaded from the latest database entry
INFO  [open_webui.env] 'ENABLE_WEB_SEARCH' loaded from the latest database entry
INFO  [open_webui.env] 'WEB_SEARCH_ENGINE' loaded from the latest database entry
INFO  [open_webui.env] 'BYPASS_WEB_SEARCH_EMBEDDING_AND_RETRIEVAL' loaded from the latest database entry
INFO  [open_webui.env] 'BYPASS_WEB_SEARCH_WEB_LOADER' loaded from the latest database entry
INFO  [open_webui.env] 'WEB_SEARCH_RESULT_COUNT' loaded from the latest database entry
INFO  [open_webui.env] 'WEB_SEARCH_DOMAIN_FILTER_LIST' loaded from the latest database entry
INFO  [open_webui.env] 'WEB_SEARCH_CONCURRENT_REQUESTS' loaded from the latest database entry
INFO  [open_webui.env] 'WEB_LOADER_ENGINE' loaded from the latest database entry
INFO  [open_webui.env] 'WEB_LOADER_CONCURRENT_REQUESTS' loaded from the latest database entry
INFO  [open_webui.env] 'ENABLE_WEB_LOADER_SSL_VERIFICATION' loaded from the latest database entry
INFO  [open_webui.env] 'WEB_SEARCH_TRUST_ENV' loaded from the latest database entry
INFO  [open_webui.env] 'OLLAMA_CLOUD_WEB_SEARCH_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'SEARXNG_QUERY_URL' loaded from the latest database entry
INFO  [open_webui.env] 'YACY_QUERY_URL' loaded from the latest database entry
INFO  [open_webui.env] 'YACY_USERNAME' loaded from the latest database entry
INFO  [open_webui.env] 'YACY_PASSWORD' loaded from the latest database entry
INFO  [open_webui.env] 'GOOGLE_PSE_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'GOOGLE_PSE_ENGINE_ID' loaded from the latest database entry
INFO  [open_webui.env] 'BRAVE_SEARCH_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'KAGI_SEARCH_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'MOJEEK_SEARCH_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'BOCHA_SEARCH_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'SERPSTACK_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'SERPSTACK_HTTPS' loaded from the latest database entry
INFO  [open_webui.env] 'SERPER_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'SERPLY_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'JINA_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'SEARCHAPI_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'SEARCHAPI_ENGINE' loaded from the latest database entry
INFO  [open_webui.env] 'SERPAPI_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'SERPAPI_ENGINE' loaded from the latest database entry
INFO  [open_webui.env] 'BING_SEARCH_V7_ENDPOINT' loaded from the latest database entry
INFO  [open_webui.env] 'BING_SEARCH_V7_SUBSCRIPTION_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'EXA_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'PERPLEXITY_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'PERPLEXITY_MODEL' loaded from the latest database entry
INFO  [open_webui.env] 'PERPLEXITY_SEARCH_CONTEXT_USAGE' loaded from the latest database entry
INFO  [open_webui.env] 'SOUGOU_API_SID' loaded from the latest database entry
INFO  [open_webui.env] 'SOUGOU_API_SK' loaded from the latest database entry
INFO  [open_webui.env] 'TAVILY_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'TAVILY_EXTRACT_DEPTH' loaded from the latest database entry
INFO  [open_webui.env] 'PLAYWRIGHT_WS_URL' loaded from the latest database entry
INFO  [open_webui.env] 'PLAYWRIGHT_TIMEOUT' loaded from the latest database entry
INFO  [open_webui.env] 'FIRECRAWL_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'FIRECRAWL_API_BASE_URL' loaded from the latest database entry
INFO  [open_webui.env] 'EXTERNAL_WEB_SEARCH_URL' loaded from the latest database entry
INFO  [open_webui.env] 'EXTERNAL_WEB_SEARCH_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'EXTERNAL_WEB_LOADER_URL' loaded from the latest database entry
INFO  [open_webui.env] 'EXTERNAL_WEB_LOADER_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'IMAGE_GENERATION_ENGINE' loaded from the latest database entry
INFO  [open_webui.env] 'ENABLE_IMAGE_GENERATION' loaded from the latest database entry
INFO  [open_webui.env] 'ENABLE_IMAGE_PROMPT_GENERATION' loaded from the latest database entry
INFO  [open_webui.env] 'AUTOMATIC1111_BASE_URL' loaded from the latest database entry
INFO  [open_webui.env] 'AUTOMATIC1111_API_AUTH' loaded from the latest database entry
INFO  [open_webui.env] 'COMFYUI_BASE_URL' loaded from the latest database entry
INFO  [open_webui.env] 'COMFYUI_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'COMFYUI_WORKFLOW' loaded from the latest database entry
INFO  [open_webui.env] 'COMFYUI_WORKFLOW' loaded from the latest database entry
INFO  [open_webui.env] 'IMAGES_OPENAI_API_BASE_URL' loaded from the latest database entry
INFO  [open_webui.env] 'IMAGES_OPENAI_API_VERSION' loaded from the latest database entry
INFO  [open_webui.env] 'IMAGES_OPENAI_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'IMAGES_GEMINI_API_BASE_URL' loaded from the latest database entry
INFO  [open_webui.env] 'IMAGES_GEMINI_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'WHISPER_MODEL' loaded from the latest database entry
INFO  [open_webui.env] 'DEEPGRAM_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'AUDIO_STT_OPENAI_API_BASE_URL' loaded from the latest database entry
INFO  [open_webui.env] 'AUDIO_STT_OPENAI_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'AUDIO_STT_ENGINE' loaded from the latest database entry
INFO  [open_webui.env] 'AUDIO_STT_MODEL' loaded from the latest database entry
INFO  [open_webui.env] 'AUDIO_STT_SUPPORTED_CONTENT_TYPES' loaded from the latest database entry
INFO  [open_webui.env] 'AUDIO_STT_AZURE_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'AUDIO_STT_AZURE_REGION' loaded from the latest database entry
INFO  [open_webui.env] 'AUDIO_STT_AZURE_LOCALES' loaded from the latest database entry
INFO  [open_webui.env] 'AUDIO_STT_AZURE_BASE_URL' loaded from the latest database entry
INFO  [open_webui.env] 'AUDIO_STT_AZURE_MAX_SPEAKERS' loaded from the latest database entry
INFO  [open_webui.env] 'AUDIO_TTS_OPENAI_API_BASE_URL' loaded from the latest database entry
INFO  [open_webui.env] 'AUDIO_TTS_OPENAI_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'AUDIO_TTS_OPENAI_PARAMS' loaded from the latest database entry
INFO  [open_webui.env] 'AUDIO_TTS_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'AUDIO_TTS_ENGINE' loaded from the latest database entry
INFO  [open_webui.env] 'AUDIO_TTS_MODEL' loaded from the latest database entry
INFO  [open_webui.env] 'AUDIO_TTS_VOICE' loaded from the latest database entry
INFO  [open_webui.env] 'AUDIO_TTS_SPLIT_ON' loaded from the latest database entry
INFO  [open_webui.env] 'AUDIO_TTS_AZURE_SPEECH_REGION' loaded from the latest database entry
INFO  [open_webui.env] 'AUDIO_TTS_AZURE_SPEECH_BASE_URL' loaded from the latest database entry
INFO  [open_webui.env] 'AUDIO_TTS_AZURE_SPEECH_OUTPUT_FORMAT' loaded from the latest database entry
INFO  [open_webui.env] 'ENABLE_LDAP' loaded from the latest database entry
WARNI [langchain_community.utils.user_agent] USER_AGENT environment variable not set, consider setting it to identify your requests.

 ██████╗ ██████╗ ███████╗███╗   ██╗    ██╗    ██╗███████╗██████╗ ██╗   ██╗██╗
██╔═══██╗██╔══██╗██╔════╝████╗  ██║    ██║    ██║██╔════╝██╔══██╗██║   ██║██║
██║   ██║██████╔╝█████╗  ██╔██╗ ██║    ██║ █╗ ██║█████╗  ██████╔╝██║   ██║██║
██║   ██║██╔═══╝ ██╔══╝  ██║╚██╗██║    ██║███╗██║██╔══╝  ██╔══██╗██║   ██║██║
╚██████╔╝██║     ███████╗██║ ╚████║    ╚███╔███╔╝███████╗██████╔╝╚██████╔╝██║
 ╚═════╝ ╚═╝     ╚══════╝╚═╝  ╚═══╝     ╚══╝╚══╝ ╚══════╝╚═════╝  ╚═════╝ ╚═╝

v0.6.34 - building the best AI user interface.

https://github.com/open-webui/open-webui

Fetching 30 files:   0%|          | 0/30 [00:00<?, ?it/s]
Fetching 30 files: 100%|██████████| 30/30 [00:00<00:00, 46125.04it/s]
/usr/local/lib/python3.11/site-packages/torch/cuda/__init__.py:283: UserWarning: 
    Found GPU0 NVIDIA GB10 which is of cuda capability 12.1.
    Minimum and Maximum cuda capability supported by this version of PyTorch is
    (8.0) - (12.0)
    
  warnings.warn(
INFO:     Started server process [1]
INFO:     Waiting for application startup.
2025-11-01 21:58:16.160 | INFO     | open_webui.utils.logger:start_logger:162 - GLOBAL_LOG_LEVEL: INFO
2025-11-01 21:58:16.160 | INFO     | open_webui.main:lifespan:561 - Installing external dependencies of functions and tools...
2025-11-01 21:58:16.165 | INFO     | open_webui.utils.plugin:install_frontmatter_requirements:283 - No requirements found in frontmatter.
2025-11-01 21:58:25.557 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "GET /_app/version.json HTTP/1.1" 304
2025-11-01 21:59:12.439 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "GET /api/v1/chats/fbe966ff-ec87-408d-a19a-bdce8f4db4e8 HTTP/1.1" 200
2025-11-01 21:59:12.463 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "GET /api/v1/chats/fbe966ff-ec87-408d-a19a-bdce8f4db4e8/tags HTTP/1.1" 200
2025-11-01 21:59:12.495 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "GET /api/v1/users/user/settings HTTP/1.1" 200
2025-11-01 21:59:12.508 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "GET /api/tasks/chat/fbe966ff-ec87-408d-a19a-bdce8f4db4e8 HTTP/1.1" 200
2025-11-01 21:59:13.195 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "GET /api/v1/tools/ HTTP/1.1" 200
2025-11-01 21:59:13.965 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "GET /api/v1/chats/bebeabfe-a8c8-409a-98df-0e86c02ca2bc HTTP/1.1" 200
2025-11-01 21:59:13.986 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "GET /api/v1/chats/bebeabfe-a8c8-409a-98df-0e86c02ca2bc/tags HTTP/1.1" 200
2025-11-01 21:59:14.009 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "GET /api/v1/users/user/settings HTTP/1.1" 200
2025-11-01 21:59:14.060 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "GET /api/tasks/chat/bebeabfe-a8c8-409a-98df-0e86c02ca2bc HTTP/1.1" 200
2025-11-01 21:59:14.552 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "GET /api/v1/tools/ HTTP/1.1" 200
2025-11-01 21:59:25.532 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "GET /_app/version.json HTTP/1.1" 304
2025-11-01 22:00:25.530 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "GET /_app/version.json HTTP/1.1" 304
2025-11-01 22:01:03.886 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "POST /api/v1/chats/bebeabfe-a8c8-409a-98df-0e86c02ca2bc HTTP/1.1" 200
2025-11-01 22:01:03.906 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "GET /api/v1/chats/?page=1 HTTP/1.1" 200
2025-11-01 22:01:03.925 | INFO     | open_webui.routers.openai:get_all_models:490 - get_all_models()
2025-11-01 22:01:03.932 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "POST /api/chat/completions HTTP/1.1" 200
2025-11-01 22:01:03.944 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "GET /api/v1/chats/?page=1 HTTP/1.1" 200
2025-11-01 22:01:25.528 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "GET /_app/version.json HTTP/1.1" 304
2025-11-01 22:01:42.414 | INFO     | open_webui.routers.openai:get_all_models:490 - get_all_models()
2025-11-01 22:01:42.441 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "POST /api/chat/completed HTTP/1.1" 200
2025-11-01 22:01:42.488 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "POST /api/v1/chats/bebeabfe-a8c8-409a-98df-0e86c02ca2bc HTTP/1.1" 200
2025-11-01 22:01:42.515 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "GET /api/v1/chats/?page=1 HTTP/1.1" 200
2025-11-01 22:01:59.599 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "POST /api/v1/chats/bebeabfe-a8c8-409a-98df-0e86c02ca2bc HTTP/1.1" 200
2025-11-01 22:01:59.613 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "GET /api/v1/chats/?page=1 HTTP/1.1" 200
2025-11-01 22:01:59.629 | INFO     | open_webui.routers.openai:get_all_models:490 - get_all_models()
2025-11-01 22:01:59.630 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "POST /api/chat/completions HTTP/1.1" 200
2025-11-01 22:01:59.643 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "GET /api/v1/chats/?page=1 HTTP/1.1" 200
2025-11-01 22:02:25.534 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "GET /_app/version.json HTTP/1.1" 304
2025-11-01 22:02:43.596 | INFO     | open_webui.routers.openai:get_all_models:490 - get_all_models()
2025-11-01 22:02:43.641 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "POST /api/chat/completed HTTP/1.1" 200
2025-11-01 22:02:43.715 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "POST /api/v1/chats/bebeabfe-a8c8-409a-98df-0e86c02ca2bc HTTP/1.1" 200
2025-11-01 22:02:43.729 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "GET /api/v1/chats/?page=1 HTTP/1.1" 200
2025-11-01 22:03:00.366 | INFO     | open_webui.routers.audio:transcription:954 - file.content_type: audio/wav
2025-11-01 22:03:00.373 | INFO     | open_webui.routers.audio:transcribe:833 - transcribe: /app/backend/data/cache/audio/transcriptions/03d6fbe1-da58-43a4-8515-dc9cf6086bc4.wav None
2025-11-01 22:03:00.633 | INFO     | open_webui.routers.audio:convert_audio_to_mp3:116 - Converted /app/backend/data/cache/audio/transcriptions/03d6fbe1-da58-43a4-8515-dc9cf6086bc4.wav to /app/backend/data/cache/audio/transcriptions/03d6fbe1-da58-43a4-8515-dc9cf6086bc4.mp3
Chunk paths: ['/app/backend/data/cache/audio/transcriptions/03d6fbe1-da58-43a4-8515-dc9cf6086bc4.mp3']
2025-11-01 22:03:00.642 | WARNING  | open_webui.routers.audio:set_faster_whisper_model:139 - WhisperModel initialization failed, attempting download with local_files_only=False
2025-11-01 22:03:00.781 | ERROR    | open_webui.routers.audio:transcription:1002 - 500: Error transcribing chunk: This CTranslate2 package was not compiled with CUDA support
Traceback (most recent call last):

  File "/app/backend/open_webui/routers/audio.py", line 137, in set_faster_whisper_model
    whisper_model = WhisperModel(**faster_whisper_kwargs)
                    │              └ {'model_size_or_path': 'base', 'device': 'cuda', 'compute_type': 'int8', 'download_root': '/app/backend/data/cache/whisper/mo...
                    └ <class 'faster_whisper.transcribe.WhisperModel'>

  File "/usr/local/lib/python3.11/site-packages/faster_whisper/transcribe.py", line 647, in __init__
    self.model = ctranslate2.models.Whisper(
    │            │           │      └ <class 'ctranslate2._ext.Whisper'>
    │            │           └ <module 'ctranslate2.models' from '/usr/local/lib/python3.11/site-packages/ctranslate2/models/__init__.py'>
    │            └ <module 'ctranslate2' from '/usr/local/lib/python3.11/site-packages/ctranslate2/__init__.py'>
    └ <faster_whisper.transcribe.WhisperModel object at 0xe4104f96ab90>

ValueError: This CTranslate2 package was not compiled with CUDA support

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/app/backend/open_webui/routers/audio.py", line 865, in transcribe
    results.append(future.result())
    │       │      │      └ <function Future.result at 0xe414451a62a0>
    │       │      └ <Future at 0xe4104fea8590 state=finished raised ValueError>
    │       └ <method 'append' of 'list' objects>
    └ []

  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           └ None
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
          └ None
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             │        │            └ None
             │        └ None
             └ None

  File "/app/backend/open_webui/routers/audio.py", line 569, in transcription_handler
    request.app.state.faster_whisper_model = set_faster_whisper_model(
    │       │                                └ <function set_faster_whisper_model at 0xe411128cdda0>
    │       └ <property object at 0xe414412facf0>
    └ <starlette.requests.Request object at 0xe4104f8d25d0>

  File "/app/backend/open_webui/routers/audio.py", line 143, in set_faster_whisper_model
    whisper_model = WhisperModel(**faster_whisper_kwargs)
                    │              └ {'model_size_or_path': 'base', 'device': 'cuda', 'compute_type': 'int8', 'download_root': '/app/backend/data/cache/whisper/mo...
                    └ <class 'faster_whisper.transcribe.WhisperModel'>

  File "/usr/local/lib/python3.11/site-packages/faster_whisper/transcribe.py", line 647, in __init__
    self.model = ctranslate2.models.Whisper(
    │            │           │      └ <class 'ctranslate2._ext.Whisper'>
    │            │           └ <module 'ctranslate2.models' from '/usr/local/lib/python3.11/site-packages/ctranslate2/models/__init__.py'>
    │            └ <module 'ctranslate2' from '/usr/local/lib/python3.11/site-packages/ctranslate2/__init__.py'>
    └ <faster_whisper.transcribe.WhisperModel object at 0xe4104fa92850>

ValueError: This CTranslate2 package was not compiled with CUDA support

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0xe414452849a0>
    └ <WorkerThread(AnyIO worker thread, started 250758132195744)>
  File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
    │    └ <function WorkerThread.run at 0xe4104f943060>
    └ <WorkerThread(AnyIO worker thread, started 250758132195744)>
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 976, in run
    result = context.run(func, *args)
             │       │   │      └ ()
             │       │   └ functools.partial(<function transcription at 0xe411129871a0>, user=UserModel(id='c5fe981f-f3bc-4078-811e-54fe5a147c2f', name=...
             │       └ <method 'run' of '_contextvars.Context' objects>
             └ <_contextvars.Context object at 0xe4104febca80>

> File "/app/backend/open_webui/routers/audio.py", line 994, in transcription
    result = transcribe(request, file_path, metadata)
             │          │        │          └ None
             │          │        └ '/app/backend/data/cache/audio/transcriptions/03d6fbe1-da58-43a4-8515-dc9cf6086bc4.wav'
             │          └ <starlette.requests.Request object at 0xe4104f8d25d0>
             └ <function transcribe at 0xe41112986e80>

  File "/app/backend/open_webui/routers/audio.py", line 867, in transcribe
    raise HTTPException(
          └ <class 'fastapi.exceptions.HTTPException'>

fastapi.exceptions.HTTPException: 500: Error transcribing chunk: This CTranslate2 package was not compiled with CUDA support
2025-11-01 22:03:00.784 | ERROR    | open_webui.routers.audio:transcription:1010 - 400: [ERROR: 500: Error transcribing chunk: This CTranslate2 package was not compiled with CUDA support]
Traceback (most recent call last):

  File "/app/backend/open_webui/routers/audio.py", line 137, in set_faster_whisper_model
    whisper_model = WhisperModel(**faster_whisper_kwargs)
                    │              └ {'model_size_or_path': 'base', 'device': 'cuda', 'compute_type': 'int8', 'download_root': '/app/backend/data/cache/whisper/mo...
                    └ <class 'faster_whisper.transcribe.WhisperModel'>

  File "/usr/local/lib/python3.11/site-packages/faster_whisper/transcribe.py", line 647, in __init__
    self.model = ctranslate2.models.Whisper(
    │            │           │      └ <class 'ctranslate2._ext.Whisper'>
    │            │           └ <module 'ctranslate2.models' from '/usr/local/lib/python3.11/site-packages/ctranslate2/models/__init__.py'>
    │            └ <module 'ctranslate2' from '/usr/local/lib/python3.11/site-packages/ctranslate2/__init__.py'>
    └ <faster_whisper.transcribe.WhisperModel object at 0xe4104f96ab90>

ValueError: This CTranslate2 package was not compiled with CUDA support

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/app/backend/open_webui/routers/audio.py", line 865, in transcribe
    results.append(future.result())
    │       │      │      └ <function Future.result at 0xe414451a62a0>
    │       │      └ <Future at 0xe4104fea8590 state=finished raised ValueError>
    │       └ <method 'append' of 'list' objects>
    └ []

  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           └ None
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
          └ None
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             │        │            └ None
             │        └ None
             └ None

  File "/app/backend/open_webui/routers/audio.py", line 569, in transcription_handler
    request.app.state.faster_whisper_model = set_faster_whisper_model(
    │       │                                └ <function set_faster_whisper_model at 0xe411128cdda0>
    │       └ <property object at 0xe414412facf0>
    └ <starlette.requests.Request object at 0xe4104f8d25d0>

  File "/app/backend/open_webui/routers/audio.py", line 143, in set_faster_whisper_model
    whisper_model = WhisperModel(**faster_whisper_kwargs)
                    │              └ {'model_size_or_path': 'base', 'device': 'cuda', 'compute_type': 'int8', 'download_root': '/app/backend/data/cache/whisper/mo...
                    └ <class 'faster_whisper.transcribe.WhisperModel'>

  File "/usr/local/lib/python3.11/site-packages/faster_whisper/transcribe.py", line 647, in __init__
    self.model = ctranslate2.models.Whisper(
    │            │           │      └ <class 'ctranslate2._ext.Whisper'>
    │            │           └ <module 'ctranslate2.models' from '/usr/local/lib/python3.11/site-packages/ctranslate2/models/__init__.py'>
    │            └ <module 'ctranslate2' from '/usr/local/lib/python3.11/site-packages/ctranslate2/__init__.py'>
    └ <faster_whisper.transcribe.WhisperModel object at 0xe4104fa92850>

ValueError: This CTranslate2 package was not compiled with CUDA support

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/app/backend/open_webui/routers/audio.py", line 994, in transcription
    result = transcribe(request, file_path, metadata)
             │          │        │          └ None
             │          │        └ '/app/backend/data/cache/audio/transcriptions/03d6fbe1-da58-43a4-8515-dc9cf6086bc4.wav'
             │          └ <starlette.requests.Request object at 0xe4104f8d25d0>
             └ <function transcribe at 0xe41112986e80>

  File "/app/backend/open_webui/routers/audio.py", line 867, in transcribe
    raise HTTPException(
          └ <class 'fastapi.exceptions.HTTPException'>

fastapi.exceptions.HTTPException: 500: Error transcribing chunk: This CTranslate2 package was not compiled with CUDA support

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0xe414452849a0>
    └ <WorkerThread(AnyIO worker thread, started 250758132195744)>
  File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
    │    └ <function WorkerThread.run at 0xe4104f943060>
    └ <WorkerThread(AnyIO worker thread, started 250758132195744)>
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 976, in run
    result = context.run(func, *args)
             │       │   │      └ ()
             │       │   └ functools.partial(<function transcription at 0xe411129871a0>, user=UserModel(id='c5fe981f-f3bc-4078-811e-54fe5a147c2f', name=...
             │       └ <method 'run' of '_contextvars.Context' objects>
             └ <_contextvars.Context object at 0xe4104febca80>

> File "/app/backend/open_webui/routers/audio.py", line 1004, in transcription
    raise HTTPException(
          └ <class 'fastapi.exceptions.HTTPException'>

fastapi.exceptions.HTTPException: 400: [ERROR: 500: Error transcribing chunk: This CTranslate2 package was not compiled with CUDA support]
2025-11-01 22:03:00.786 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "POST /api/v1/audio/transcriptions HTTP/1.1" 400
2025-11-01 22:03:25.540 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "GET /_app/version.json HTTP/1.1" 304
2025-11-01 22:04:25.538 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "GET /_app/version.json HTTP/1.1" 304
2025-11-01 22:05:25.540 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "GET /_app/version.json HTTP/1.1" 304
2025-11-01 22:05:35.768 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.21:0 - "GET /_app/version.json HTTP/1.1" 304
2025-11-01 22:06:25.536 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "GET /_app/version.json HTTP/1.1" 304
2025-11-01 22:07:08.637 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.41:0 - "GET /_app/version.json HTTP/1.1" 200
2025-11-01 22:07:25.540 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "GET /_app/version.json HTTP/1.1" 304
2025-11-01 22:08:25.540 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "GET /_app/version.json HTTP/1.1" 304
2025-11-01 22:09:25.538 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "GET /_app/version.json HTTP/1.1" 304
2025-11-01 22:10:25.539 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "GET /_app/version.json HTTP/1.1" 304
2025-11-01 22:11:25.541 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "GET /_app/version.json HTTP/1.1" 304
2025-11-01 22:12:25.539 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "GET /_app/version.json HTTP/1.1" 304
2025-11-01 22:13:25.542 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "GET /_app/version.json HTTP/1.1" 200
2025-11-01 22:14:25.537 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "GET /_app/version.json HTTP/1.1" 304
2025-11-01 22:15:25.539 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.0.10.26:0 - "GET /_app/version.json HTTP/1.1" 200

**Comment by silentoplayz** [comment]
Possibly related based on `CTranslate2` search match - https://github.com/open-webui/open-webui/discussions/10576

**Comment by tjbck** [comment]
@chris4prez this might be dgx exclusive, could you confirm?

**Reply by chris4prez** [reply]
Unfortunately I have no additional GPU environments to test from at the moment.

**Reply by gonzalo** [reply]
I can confirm this is happeing for me in a dgx fresh enviroment

**Reply by drichfsu** [reply]
I can confirm on a ThinkStation PGX Small Form Factor Workstation which has the identical hardware to the DGX the same issue is happening to me.

**Comment by eXt73** [comment]
I confirm - the same error on GH200

<img width="592" height="212" alt="Zrzut ekranu_20251127_125026" src="https://github.com/user-attachments/assets/22190993-3ad7-4149-8b0d-08ad2ecaae07" />

> Error transcribing chunk: This CTranslate2 package was not compiled with CUDA support

**Comment by AlexanderSkachkov** [comment]
Same for me on the ASUS GX10
<img width="619" height="198" alt="image" src="https://github.com/user-attachments/assets/13b53080-bf4d-4cca-be86-0d742f77113c" />

**Comment by ordex** [comment]
is there any known workaround at the moment?

**Reply by AlexanderSkachkov** [reply]
I just installed it natively (Python/uv), and it works fine.

**Reply by ordex** [reply]
I presume this doesn't work in a docker container?

**Reply by AlexanderSkachkov** [reply]
I tried to recompile CTranslate and put it inside a container, but just received new errors... If you really want to use container deployment, you can try to use one of the NVIDIAs DGX spark ready ones as basis and install OpenWebUI there.

**Reply by ordex** [reply]
well, adding a CUDA compatible CTranslate to the container is the way to go, I think

**Comment by j3sk0** [comment]
any update for this issu?
