### DISCUSSION TITLE
docker run open-webui:cuda error

### DISCUSSION THREAD

**Discussion by SunMacArenas** [open-webui/open-webui#5021] [General]
# Bug Report

## Installation Method

docker 

## Environment

- **Open WebUI Version:openwebui:cuda  v0.3.16
- **Ollama (if applicable):v0.38
ubuntu 24.04 
 NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6
docker run -d -p 18080:8080 --gpus all --network=myNet --ip=172.10.1.4 -v /mnt/docker/open-webui:/app/backend/data -e OLLAMA_BASE_URL=http://172.10.1.3:11434  --name open-webui --restart always ghcr.io/open-webui/open-webui:cuda
docker logs:
Loading WEBUI_SECRET_KEY from file, not provided as an environment variable.
Generating WEBUI_SECRET_KEY
Loading WEBUI_SECRET_KEY from .webui_secret_key
CUDA is enabled, appending LD_LIBRARY_PATH to include torch/cudnn & cublas libraries.
Failed to initialize the database connection: database is locked
/app
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/peewee.py", line 3322, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: database is locked
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
*

it seems like can not open webui.db

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by dekiesel** [comment]
I'm seeing this issue too. I am not sure how to investigate. I am trying to run openwebui as an azure container app, with `/app/backend/data` being in azure files ( as a samba share).

The only file written is 'webui.db' and it's 0 bytes. I deleted it and restarted the container, but openwebui just recreated it and then complained about it being locked.

```
2025-04-23T08:47:12.6723593Z stdout F Loading WEBUI_SECRET_KEY from .webui_secret_ke
2025-04-23T08:47:12.6736101Z stdout F CUDA is enabled, appending LD_LIBRARY_PATH to include torch/cudnn & cublas libraries.
2025-04-23T08:47:23.0918902Z stderr F Failed to initialize the database connection: database is locked
2025-04-23T08:47:23.0924087Z stderr F Traceback (most recent call last):
2025-04-23T08:47:23.0924196Z stderr F   File "/usr/local/lib/python3.11/site-packages/peewee.py", line 3322, in execute_sql
2025-04-23T08:47:23.0924280Z stdout F /app/backend/open_webui
2025-04-23T08:47:23.0924656Z stdout F /app/backend
2025-04-23T08:47:23.0924695Z stdout F /app
2025-04-23T08:47:23.0929414Z stderr F     cursor.execute(sql, params or ())
2025-04-23T08:47:23.0929873Z stderr F sqlite3.OperationalError: database is locked```

**Reply by dekiesel** [reply]
Problem solved for me: I needed to tell azure files to avoid locking by adding this to the mount options of the samba-share: `nobrl`

https://learn.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/storage/mountoptions-settings-azure-files
